### ISSUE TITLE
Warning message for unplaced images

### ISSUE THREAD

**Issue by amyshim** [TheMITTech/prototype-rails#413]
Upon saving the article, show warning message.

**Comment by tareqdandachi** [comment]
@amyshim do you mean show a warning message for every article being saved that doesn't have an image? (Are all articles encouraged to have images, so doing this promotes including images by reminding authors?)

**Comment by amyshim** [comment]
Hey, im glad youre going through these. I dont really remember the answer to your questions because I havent looked at the site in like a year. I will try to clarify sometime in the next couple weeks, but honestly, I think it would be faster to use your own discretion :) also ask Jiahao!
