### ISSUE TITLE
Diff system for articles in CMS

### ISSUE THREAD

**Issue by amyshim** [TheMITTech/prototype-rails#429]
Preliminary work done using diffy gem. Delegated to Jiahao Li for styling, and probably want to add diff for metadata fields as well.

**Comment by isundaylee** [comment]
This feature has since been implemented separate from this issue. See attached screenshot: 

![screen shot 2017-11-08 at 3 31 14 pm](https://user-images.githubusercontent.com/1572861/32572857-00aad9e2-c49a-11e7-9275-0c6daa72ba45.png)
