### ISSUE TITLE
Fourth author in byline erases author list

### ISSUE THREAD

**Issue by wolfiang** [TheMITTech/prototype-rails#499]
Hello,

Apparently if you try adding more than three people in the "Authors" box in the CMS, the fourth author erases the author listing in the preview of the article in the CMS. Could we change it so that articles can support having several authors? Or maybe raising the limit to a number we will probably never reach, like 10.

![four authors in cms](https://user-images.githubusercontent.com/35787693/54332142-3d571f00-45f3-11e9-8da3-6bd796dcf918.PNG)

![no authors shown](https://user-images.githubusercontent.com/35787693/54332153-4cd66800-45f3-11e9-8b13-c95ca140a95d.PNG)

Thanks!

**Comment by isundaylee** [comment]
I have located the bug, and will work on a fix tomorrow. Ping me in a couple days if I fail to report back here. Thanks!

**Comment by isundaylee** [comment]
Fixed in @2222ec8
